<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\JobApplicationTrackerAPI.DAL\JobApplicationTrackerAPI.DAL.csproj" />
    <ProjectReference Include="..\JobApplicationTrackerAPI.Models\JobApplicationTrackerAPI.Models.csproj" />
  </ItemGroup>

</Project>
