// <auto-generated />
using System;
using JobApplicationTrackerAPI.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobApplicationTrackerAPI.DAL.Migrations
{
    [DbContext(typeof(JobApplicationTrackerDbContext))]
    [Migration("20260929234220_UpdateCompanyWebsiteUrlMaxLength")]
    partial class UpdateCompanyWebsiteUrlMaxLength
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApplicationSkill", b =>
                {
                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("ApplicationId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("ApplicationSkill");

                    b.HasData(
                        new
                        {
                            ApplicationId = 1,
                            SkillId = 1
                        },
                        new
                        {
                            ApplicationId = 1,
                            SkillId = 2
                        },
                        new
                        {
                            ApplicationId = 1,
                            SkillId = 5
                        },
                        new
                        {
                            ApplicationId = 2,
                            SkillId = 3
                        },
                        new
                        {
                            ApplicationId = 2,
                            SkillId = 4
                        });
                });

            modelBuilder.Entity("JobApplicationTrackerAPI.Models.Application", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationId"));

                    b.Property<DateTime>("AppliedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("JobUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<decimal?>("SalaryMax")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SalaryMin")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ApplicationId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId");

                    b.ToTable("Application", (string)null);

                    b.HasData(
                        new
                        {
                            ApplicationId = 1,
                            AppliedDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompanyId = 1,
                            JobTitle = "Full Stack Developer",
                            JobUrl = "https://techcorp.example.com/careers/123",
                            SalaryMax = 95000m,
                            SalaryMin = 80000m,
                            Status = "Interviewing",
                            UserId = 1
                        },
                        new
                        {
                            ApplicationId = 2,
                            AppliedDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompanyId = 2,
                            JobTitle = "Frontend Engineer",
                            JobUrl = "https://innovatesolutions.example.com/careers/456",
                            SalaryMax = 90000m,
                            SalaryMin = 75000m,
                            Status = "Applied",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("JobApplicationTrackerAPI.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WebsiteUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("CompanyId");

                    b.ToTable("Company", (string)null);

                    b.HasData(
                        new
                        {
                            CompanyId = 1,
                            Industry = "Software Development",
                            Location = "Winnipeg, MB",
                            Name = "TechCorp",
                            WebsiteUrl = "https://techcorp.example.com"
                        },
                        new
                        {
                            CompanyId = 2,
                            Industry = "Fintech",
                            Location = "Remote",
                            Name = "Innovate Solutions",
                            WebsiteUrl = "https://innovatesolutions.example.com"
                        });
                });

            modelBuilder.Entity("JobApplicationTrackerAPI.Models.Interview", b =>
                {
                    b.Property<int>("InterviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterviewId"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<string>("InterviewerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("InterviewId");

                    b.HasIndex("ApplicationId");

                    b.ToTable("Interview", (string)null);

                    b.HasData(
                        new
                        {
                            InterviewId = 1,
                            ApplicationId = 1,
                            InterviewerName = "Sarah Jenkins",
                            IsCompleted = true,
                            Notes = "System design discussion and live coding challenge in C#.",
                            ScheduledAt = new DateTime(2026, 3, 10, 14, 0, 0, 0, DateTimeKind.Utc),
                            StageName = "Technical Screening"
                        });
                });

            modelBuilder.Entity("JobApplicationTrackerAPI.Models.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SkillId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skill", (string)null);

                    b.HasData(
                        new
                        {
                            SkillId = 1,
                            Category = "Backend",
                            Name = "C#"
                        },
                        new
                        {
                            SkillId = 2,
                            Category = "Backend",
                            Name = ".NET Core"
                        },
                        new
                        {
                            SkillId = 3,
                            Category = "Frontend",
                            Name = "React"
                        },
                        new
                        {
                            SkillId = 4,
                            Category = "Frontend",
                            Name = "TypeScript"
                        },
                        new
                        {
                            SkillId = 5,
                            Category = "Database",
                            Name = "SQL Server"
                        });
                });

            modelBuilder.Entity("JobApplicationTrackerAPI.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alex.morgan@example.com",
                            FirstName = "Alex",
                            LastName = "Morgan",
                            PasswordHash = "AQAAAAEAACcQAAAAEHhashedpasswordexample=="
                        });
                });

            modelBuilder.Entity("ApplicationSkill", b =>
                {
                    b.HasOne("JobApplicationTrackerAPI.Models.Application", null)
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobApplicationTrackerAPI.Models.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobApplicationTrackerAPI.Models.Application", b =>
                {
                    b.HasOne("JobApplicationTrackerAPI.Models.Company", "Company")
                        .WithMany("Applications")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobApplicationTrackerAPI.Models.User", "User")
                        .WithMany("Applications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobApplicationTrackerAPI.Models.Interview", b =>
                {
                    b.HasOne("JobApplicationTrackerAPI.Models.Application", "Application")
                        .WithMany("Interviews")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("JobApplicationTrackerAPI.Models.Application", b =>
                {
                    b.Navigation("Interviews");
                });

            modelBuilder.Entity("JobApplicationTrackerAPI.Models.Company", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("JobApplicationTrackerAPI.Models.User", b =>
                {
                    b.Navigation("Applications");
                });
#pragma warning restore 612, 618
        }
    }
}
